### ISSUE TITLE
Hiccups getting started

### ISSUE THREAD

**Issue by jbellis** [phact/fastastra#1]
- need to add astra_assistants as a requirement or remove the `patch` invocation (not sure what functionality is being added)
- Example in README is missing the import for `List` (`embedding=List[float]`)
- `AstraDatabase(token, dbid, embedding_model="embed-english-v3.0")` fails with `openai.InternalServerError`, I think it is because litellm isn't actually wired up and fastastra still assumes that all models are openai models

**Comment by phact** [comment]
Thanks for the feedback!

1) I'll add the dependency, it doesn't hurt. I had it in optional dependencies https://github.com/phact/fastastra/blob/main/pyproject.toml#L41 because it's not strictly needed if you're not using ANN or assistants but I guess this does more harm than good.

2) Will fix, actually `list` works too so I'll just do that.

3) This should be related to 1. The patch wires up litellm.

**Comment by phact** [comment]
done in v0.1.30
